-- Extend NotificationType with full work-order lifecycle values
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_REASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_EN_ROUTE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_IN_PROGRESS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WORK_ORDER_FAILED';
